[project]
name = "soap-jax"
version = "0.2.0"
description = "SOAP Optimizer implemented in JAX"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = ["chex", "jax", "jaxtyping", "optax"]

[build-system]
requires = ["uv_build>=0.8.5"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "B", "SIM", "I", "FURB"]
ignore = ["B905"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "equinox>=0.13.2",
    "flax>=0.10.7",
    "ipython>=8.39.0",
    "jax[cuda13]>0.6.0 ; sys_platform == 'linux'",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
    "ty>=0.0.31",
]
